name: Laravel CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: DB_flarum
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate unique version label
        id: generate_version
        run: echo "VERSION_LABEL=$(date +%s)-${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

  deployment:
      needs: build
      runs-on: ubuntu-latest
      environment: production

      steps:
        - name: Set up AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Generate deployment package
          run: zip -r deploy.zip .

        - name: Deploy to Elastic Beanstalk
          uses: einaregilsson/beanstalk-deploy@v18
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: flarum
            environment_name: pro-JBRHDO-08masw
            version_label: ${{ env.VERSION_LABEL }}
            region: us-east-1
            deployment_package: deploy.zip
